### PR TITLE
Compatibility with Mongoid 6

### PR DESCRIPTION
**Pull request by jbach**
Seems like `mongoid-shell` already works with Mongoid 6. I figured, I should still introduce v6 formally though.

### CODE REVIEW

**Comment by dblock** [comment]
The build is failing, the version of Ruby used is too old for mongoid 6. Feel free to remove all the old rubies and just leave 2.3.1.

**Comment by jbach** [comment]
Hey @dblock,
seems like [rubocop@0.32.1](https://github.com/bbatsov/rubocop/blob/0925327a968f176b470e886ead8c0eb6b9a7e006/lib/rubocop/rake_task.rb#L23) uses `::Rake.application.last_comment`, which leads to a [deprecation warning](https://travis-ci.org/mongoid/mongoid-shell/jobs/180429926#L234) when building with 2.3.0 but [breaks the build](https://travis-ci.org/mongoid/mongoid-shell/jobs/182349578#L240) in 2.3.1.

**Comment by dblock** [comment]
You should just upgrade Rubocop, new version then `rubocop -a` and `rubocop --auto-gen-config` should do the trick.

**Comment by dblock** [comment]
Merged, thank you.

**Comment by dblock** [comment]
@jbach Looks like you're using this gem. Want to help out with a release? I can give you access - just need your rubygems email.

**Comment by dblock** [comment]
Better late than never, cut 0.4.4.

**Pull request merged**
